unique_ids:
  forms:
    Form1: ILRRHVQ2S4TB56Q2RLWWKLETDZ675SMI
    Form1.ItemTemplate1: '1717188569744509055033733.43555'
  modules: {}
  server_modules: {}
  assets:
    icon.png: '1717189124299413237880968.0114'
    standard-page.html: 4YDJ4VJTU5FBEWLHJMYLGQPHBYPJ64EE
    theme.css: LZYRPQZASYUSH6U2ZDBPUBFMD4ORW7GO
  scripts: {}
